name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # This is the folder with your static content

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
